### PR TITLE
Introducing string expression to ensure replication_group_id max lenght does not exceed 20 chars

### PR DESCRIPTION
**Pull request by seancrow**
Hi @zmoog this is the patch I would like to introduce to ensure replication_group_id length doesn't exceed 20 chars, as per AWS resource limit

### CODE REVIEW

**Comment by zmoog** [comment]
I agree that limiting the RG name to the underlying 20 char limit is useful.

I'd like to preserve the third element in the naming convention alongside the _project_ and _environment_ element. 

This element could be called _name_ and be optional (set to _BLANK_ by default). A third element could be useful in scenarios where more than one RG is required.

If you can't do the change now I'love leave this PR open and apply this change later. In the meantime you can use the pre-release tag in your project and not wait form me.

Thank you for taking the time to write and submit this PR!

**Comment by seancrow** [comment]
OK @zmoog, I will try to update this same PR to reflect your suggestions. 
The only problem IMO I see is that by using a third element, appended at the end of the replication_group_id, it would become more complicated to calculate the length at which "cut" the whole string..

**Comment by seancrow** [comment]
OK @zmoog, I will try to update this same PR to reflect your suggestions.

The only problem IMO is that by using a third element to specify an RG suffix (where required), appending it at the end of the replication_group_id expression, calculating the right length at which to "cut" the whole string can become a little tricky.
Please let me know if the solution I will come up with can be acceptable, so we can merge these changes promoting them

Cheers!

**Comment by seancrow** [comment]
Hi @zmoog! At last I think to have come up with a viable solution. I'va added a second replace() + regexps call, to ensure _replication_group_id_ does not end with an hyphen character, which is not permitted.

I'va played around a bit with both regexps (particularly with the second one, using https://regex101.com/r/eP2qF4/1) to verify them a bit.

The last test I did is was executing a `terraform plan` against known environments (_dev_, _alpha_, _beta-*_), verifying plan results were as expected (i.e.: no resources to modify and/or destroy to be then created anew).

Please check my proposal to see if everything's ok and mergeable.

Thanx!

**Comment by zmoog** [comment]
@seancrow thank you for your useful and kind contribution!

**Pull request merged**
